### ISSUE TITLE
Debug tunirtests.atomictests.TestDockerStorageSetup errors for Fedora 22 atomic image

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/tunirtests#3]
command: sudo python3 -m unittest tunirtests.atomictests.TestDockerStorageSetup -v
status: False

test_journalctl_logs (tunirtests.atomictests.TestDockerStorageSetup)
Test journalctl logs for docker-storage-setup ... FAIL
test_lsblk_output (tunirtests.atomictests.TestDockerStorageSetup)
Test output for lsblk ... FAIL
# 

FAIL: test_journalctl_logs (tunirtests.atomictests.TestDockerStorageSetup)
## Test journalctl logs for docker-storage-setup

Traceback (most recent call last):
  File "/var/home/fedora/tunirtests/atomictests.py", line 25, in test_journalctl_logs
    self.assertTrue(re.search(r'CHANGED: partition=\d', out))
AssertionError: None is not true
# 

FAIL: test_lsblk_output (tunirtests.atomictests.TestDockerStorageSetup)
## Test output for lsblk

Traceback (most recent call last):
  File "/var/home/fedora/tunirtests/atomictests.py", line 45, in test_lsblk_output
    re.search(r'atomicos-docker--meta._\d+(?:.\d+)?M._lvm', out)
AssertionError: None is not true

---

Ran 2 tests in 0.025s

FAILED (failures=2)

The image is https://kojipkgs.fedoraproject.org//work/tasks/8562/11578562/Fedora-Cloud-Atomic-22-20151026.x86_64.qcow2

**Comment by kushaldas** [comment]
Initial debugging found https://github.com/kushaldas/tunirtests/blob/master/atomictests.py#L17 followed the output from http://fedoraproject.org/wiki/User:Roshi/QA/AtomicTests/Atomic_Docker_Storage_Setup

But the actual output is different on the cloud images.

$ sudo journalctl -o cat --unit docker-storage-setup.service
Starting Docker Storage Setup...
Rounding up size to full physical extent 8.00 MiB
Logical volume "docker-poolmeta" created.
DATA_SIZE=40%FREE is smaller than MIN_DATA_SIZE=2G. Will create data volume of size specified by MIN_DATA_SIZE.
Logical volume "docker-pool" created.
WARNING: Converting logical volume atomicos/docker-pool and atomicos/docker-poolmeta to pool's data and metadata volumes.
THIS WILL DESTROY CONTENT OF LOGICAL VOLUME (filesystem etc.)
Converted atomicos/docker-pool to thin pool.
Logical volume "docker-pool" changed.
Started Docker Storage Setup.
$ lsblk
NAME                            MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vda                             252:0    0     6G  0 disk 
├─vda1                          252:1    0   300M  0 part /boot
└─vda2                          252:2    0   5.7G  0 part 
  ├─atomicos-root               253:0    0     3G  0 lvm  /sysroot
  ├─atomicos-docker--pool_tmeta 253:1    0     8M  0 lvm  
  │ └─atomicos-docker--pool     253:3    0     2G  0 lvm  
  └─atomicos-docker--pool_tdata 253:2    0     2G  0 lvm  
    └─atomicos-docker--pool     253:3    0     2G  0 lvm  
vdb                             252:16   0 286.5K  0 disk

**Comment by kushaldas** [comment]
It seems docker-storage-setup is failing due to no space.

**Comment by kushaldas** [comment]
https://github.com/kushaldas/tunir/issues/22 was done to solve this.
